resources:
  - url: http://127.0.0.1:5000/apple-tv-remote.js
    type: module
views:
  - cards:
      - type: custom:apple-tv-remote
        name: Apple TV Remote Development
        entity: null
        test_gui: true
