name: "Validate HACS repo & build"

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  validate:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: "hacs/action@main"
        with:
          category: "plugin"

  build:
    name: Build and commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run build
      - name: Commit build artifacts
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "bramn@users.noreply.github.com"
          git commit -a -m "Build by Github Actions"
          git push
